[package]
org = "snowflake_integration"
name = "sap_concur_etl"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "snowflake"
version = "2.2.0"

[[dependency]]
org = "ballerinax"
name = "snowflake.driver"
version = "2.8.0"