[package]
org = "snowflake_integration"
name = "sap_concur_etl"
version = "0.1.0"
distribution = "2201.12.7"
description = "SAP Concur to Snowflake ETL Integration Service"
keywords = ["etl", "snowflake", "sap-concur", "data-integration"]
authors = ["Your Name <your.email@company.com>"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.0"

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.9.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.5.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.10.0"

[[dependency]]
org = "ballerinax"
name = "snowflake"
version = "2.2.0"

[[dependency]]
org = "ballerinax"
name = "snowflake.driver"
version = "2.8.0"

[[platform.java17.dependency]]
groupId = "net.snowflake"
artifactId = "snowflake-jdbc"
version = "3.13.33"
