[package]
org = "snowflake_integration"
name = "sap_concur_etl"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

# Package description and metadata
description = "SAP Concur to Snowflake ETL Integration Service"
keywords = ["etl", "snowflake", "sap-concur", "data-integration"]
authors = ["Muhammad Ali <muhammad@wso2.com>"]
license = "Apache-2.0"

[[dependency]]
org = "ballerinax"
name = "snowflake"
version = "2.2.0"

[[dependency]]
org = "ballerinax"
name = "snowflake.driver"
version = "2.8.0"