[container.image]
repository = "snowflake_integration"
name = "sap_concur_etl"
tag = "latest"

[cloud.config.envs]
hostName = "0.0.0.0"
servicePort = 8080
etlServicePort = 8082
sapConcurPort = 8081
snowflakeWarehouse = "COMPUTE_WH"
snowflakeSchema = "PUBLIC"
sapConcurApiKey = "mock-api-key"

[cloud.config.secrets]
snowflakeAccount = "SNOWFLAKE_ACCOUNT"
snowflakeUser = "SNOWFLAKE_USER"
snowflakePassword = "SNOWFLAKE_PASSWORD"
snowflakeDatabase = "SNOWFLAKE_DATABASE"