# Configuration for local development
hostName = "localhost"
snowflakeAccount = "MELBZZN-YYB45887"
snowflakeUser = "MUHAMMAD"
snowflakePassword = "3f2Uj8B3LGwikgZ"
snowflakeDatabase = "COMPANY_DB"
snowflakeWarehouse = "BALLERINA"
snowflakeSchema = "PUBLIC"
servicePort = 8080
etlServicePort = 8082
sapConcurPort = 8081
sapConcurApiKey = "mock-api-key"